services:
  backend-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: backend-api-service-image

    ports: 
      - "3000:3000"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules